name: muslim_day
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  adhan: ^2.0.0-nullsafety.2
  hijri: ^3.0.0
  # table_calendar: ^3.1.2
  flutter_compass: ^0.8.0
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  geolocator: ^12.0.0
  quran: ^1.2.4
  google_fonts: ^6.2.1 
  http: ^1.2.1
  flutter_markdown: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # !! IMPORTANT !!
  # Make sure you have added your data files here
  # assets:
    # - lib/data/bn_translation.json
    # - lib/data/bangladesh_districts.dart